const MOCK_USER={id:"KC-2048",name:"Amina Njeri",electricityUsageKwh:42.6,creditKes:1250,profilePhotoUrl:"assets/profile-photo.svg"};
const DEFAULT_REWARD_BY_LEVEL={low:30,medium:15,high:0};
const DEFAULT_USAGE_KWH=.6;
let HOURLY_TARIFFS=Array.from({length:24},(_,hour)=>{let level="low",rateKesPerKwh=17;if(hour>=10&&hour<=15){level="low";rateKesPerKwh=15}else if((hour>=6&&hour<=9)||(hour>=16&&hour<=17)||hour===23){level="medium";rateKesPerKwh=25}else if(hour>=18&&hour<=22){level="high";rateKesPerKwh=38}return{hour,level,rateKesPerKwh,rewardCreditKes:DEFAULT_REWARD_BY_LEVEL[level],estimatedKwh:DEFAULT_USAGE_KWH}});
const selectedHours=new Set();let availableTariffs=[],lastFocusedElement=null,popoverTimer=null,scrollUpdateFrame=null,toastTimer=null;
const $=s=>document.querySelector(s);
const el={userId:$("#userId"),userName:$("#userName"),electricityUsage:$("#electricityUsage"),creditBalance:$("#creditBalance"),profilePhoto:$("#profilePhoto"),profileButton:$("#profileButton"),timeViewport:$("#timeViewport"),timeTrack:$("#timeTrack"),previousButton:$("#previousButton"),nextButton:$("#nextButton"),pageIndicator:$("#pageIndicator"),remainingHoursText:$("#remainingHoursText"),selectionSummary:$("#selectionSummary"),clearButton:$("#clearButton"),goButton:$("#goButton"),slotPopover:$("#slotPopover"),popoverTitle:$("#popoverTitle"),popoverText:$("#popoverText"),resultsModal:$("#resultsModal"),closeModalButton:$("#closeModalButton"),doneButton:$("#doneButton"),totalCredit:$("#totalCredit"),totalUsage:$("#totalUsage"),selectedCount:$("#selectedCount"),selectedHourChips:$("#selectedHourChips"),recommendationTitle:$("#recommendationTitle"),recommendationText:$("#recommendationText"),resultBadge:$("#resultBadge"),toast:$("#toast")};
function formatHourParts(hour){const h=hour%24,p=h<12?"AM":"PM",n=h%12||12;return{number:n,period:p,full:`${n}:00 ${p}`}}
function formatTimeRange(hour){return`${formatHourParts(hour).full}–${formatHourParts((hour+1)%24).full}`}
function formatKes(v){return new Intl.NumberFormat("en-KE",{maximumFractionDigits:0}).format(v)}
function formatCredit(v){return new Intl.NumberFormat("en-KE",{minimumFractionDigits:2,maximumFractionDigits:2}).format(v)}
function getVisibleCount(){return innerWidth<=360?2:innerWidth>=420?4:3}
function getCurrentHour(){return new Date().getHours()}
function getTariff(hour){return HOURLY_TARIFFS.find(x=>x.hour===hour)}
function getCostLabel(level){return{low:"Lower cost",medium:"Average cost",high:"Peak cost"}[level]}
function normalizeTariff(item,index){const level=item.level;return{hour:index,level,rateKesPerKwh:Number(item.rateKesPerKwh??0),rewardCreditKes:Number(item.rewardCreditKes??DEFAULT_REWARD_BY_LEVEL[level]),estimatedKwh:Number(item.estimatedKwh??DEFAULT_USAGE_KWH)}}
function setUserData(user){el.userId.textContent=user.id;el.userName.textContent=user.name;el.electricityUsage.textContent=Number(user.electricityUsageKwh).toFixed(1);el.creditBalance.textContent=formatKes(user.creditKes);el.profilePhoto.src=user.profilePhotoUrl||"assets/profile-photo.svg";el.profilePhoto.alt=`${user.name}'s profile`}
function setHourlyTariffs(tariffs){const ok=Array.isArray(tariffs)&&tariffs.length===24&&tariffs.every((x,i)=>x.hour===i&&["low","medium","high"].includes(x.level));if(!ok)throw new Error("Tariffs must contain 24 ordered hourly items with hour and level.");HOURLY_TARIFFS=tariffs.map(normalizeTariff);buildAvailableTariffs();renderTimeSlots()}
function buildAvailableTariffs(){const now=getCurrentHour();availableTariffs=HOURLY_TARIFFS.filter(x=>x.hour>=now);if(!availableTariffs.length)availableTariffs=[getTariff(23)];const valid=new Set(availableTariffs.map(x=>x.hour));[...selectedHours].forEach(h=>{if(!valid.has(h))selectedHours.delete(h)});el.remainingHoursText.textContent=`${availableTariffs.length} hour${availableTariffs.length===1?"":"s"} remaining today`}
function renderTimeSlots(){const now=getCurrentHour();el.timeTrack.innerHTML="";availableTariffs.forEach(t=>{const p=formatHourParts(t.hour),b=document.createElement("button");b.type="button";b.className=`time-slot ${t.level}${t.hour===now?" has-now":""}`;b.dataset.hour=String(t.hour);b.setAttribute("aria-pressed",String(selectedHours.has(t.hour)));b.setAttribute("aria-label",`${formatTimeRange(t.hour)}, ${getCostLabel(t.level)}, reward KES ${formatCredit(t.rewardCreditKes)}`);b.innerHTML=`${t.hour===now?'<span class="now-badge">Now</span>':""}<span class="time-number">${p.number}:00</span><span class="time-period">${p.period}</span><span class="time-cost">${getCostLabel(t.level)}</span>`;b.addEventListener("click",()=>toggleHour(t.hour,b));el.timeTrack.appendChild(b)});el.timeViewport.scrollLeft=0;updateSelectionUI();updateCarouselControls()}
function toggleHour(hour,button){if(selectedHours.has(hour)){selectedHours.delete(hour);hideSlotPopover()}else{selectedHours.add(hour);showCreditPopover(button,getTariff(hour))}updateSelectionUI()}
function getSelectedTariffs(){return[...selectedHours].sort((a,b)=>a-b).map(getTariff)}
function calculateTotals(){return getSelectedTariffs().reduce((a,t)=>({creditKes:a.creditKes+t.rewardCreditKes,usageKwh:a.usageKwh+t.estimatedKwh}),{creditKes:0,usageKwh:0})}
function updateSelectionUI(){document.querySelectorAll(".time-slot").forEach(b=>b.setAttribute("aria-pressed",String(selectedHours.has(Number(b.dataset.hour)))));const s=getSelectedTariffs(),tot=calculateTotals();el.selectionSummary.textContent=s.length?`${s.length} hour${s.length===1?"":"s"} selected · Estimated reward: KES ${formatCredit(tot.creditKes)}.`:"No cooking hours selected.";el.goButton.disabled=!s.length}
function showCreditPopover(button,t){clearTimeout(popoverTimer);const r=button.getBoundingClientRect(),half=120,x=Math.min(innerWidth-half,Math.max(half,r.left+r.width/2));el.slotPopover.style.left=`${x}px`;el.slotPopover.style.top=`${Math.max(80,r.top)}px`;el.popoverTitle.textContent=`${formatHourParts(t.hour).full} selected`;el.popoverText.textContent=t.rewardCreditKes>0?`You can earn KES ${formatCredit(t.rewardCreditKes)} credit for this hour.`:"There is no bonus credit during this peak-cost hour.";el.slotPopover.classList.remove("is-hidden");popoverTimer=setTimeout(hideSlotPopover,2200)}
function hideSlotPopover(){clearTimeout(popoverTimer);el.slotPopover.classList.add("is-hidden")}
function getPageCount(){return Math.max(1,Math.ceil(availableTariffs.length/getVisibleCount()))}
function getCurrentPage(){const w=Math.max(1,el.timeViewport.clientWidth);return Math.min(getPageCount()-1,Math.max(0,Math.round(el.timeViewport.scrollLeft/w)))}
function updateCarouselControls(){const max=el.timeViewport.scrollWidth-el.timeViewport.clientWidth;el.previousButton.disabled=el.timeViewport.scrollLeft<=4;el.nextButton.disabled=max<=4||el.timeViewport.scrollLeft>=max-4;el.pageIndicator.textContent=`${getCurrentPage()+1} / ${getPageCount()}`}
function scrollCarousel(dir){hideSlotPopover();el.timeViewport.scrollBy({left:dir*el.timeViewport.clientWidth,behavior:"smooth"})}
function scheduleCarouselControlUpdate(){if(scrollUpdateFrame)cancelAnimationFrame(scrollUpdateFrame);scrollUpdateFrame=requestAnimationFrame(updateCarouselControls)}
function renderResults(){const s=getSelectedTariffs(),tot=calculateTotals();el.totalCredit.textContent=formatCredit(tot.creditKes);el.totalUsage.textContent=tot.usageKwh.toFixed(1);el.selectedCount.textContent=`${s.length} hour${s.length===1?"":"s"}`;el.selectedHourChips.innerHTML="";s.forEach(t=>{const chip=document.createElement("span");chip.className=`hour-chip ${t.level}`;chip.textContent=formatHourParts(t.hour).full;el.selectedHourChips.appendChild(chip)});updateRecommendation(s,tot)}
function updateRecommendation(s,tot){const low=s.filter(t=>t.level==="low").length,high=s.filter(t=>t.level==="high").length,best=[...availableTariffs].sort((a,b)=>b.rewardCreditKes-a.rewardCreditKes)[0];el.resultBadge.textContent=`KES ${formatCredit(tot.creditKes)} reward`;if(low===s.length){el.recommendationTitle.textContent="Excellent low-cost plan";el.recommendationText.textContent="All selected hours are in the lower-cost period, so you receive the highest available reward."}else if(low>0){el.recommendationTitle.textContent="Your plan includes rewarded hours";el.recommendationText.textContent="You selected a mixture of cost periods. Green hours contribute the highest credit."}else if(high===s.length){el.recommendationTitle.textContent="Consider a rewarded green hour";el.recommendationText.textContent=`Your selected hours are all peak-cost. ${formatTimeRange(best.hour)} currently offers the highest credit.`}else{el.recommendationTitle.textContent="A higher-credit option is available";el.recommendationText.textContent=`${formatTimeRange(best.hour)} currently offers the highest reward among the remaining hours.`}}
function openResultsModal(){hideSlotPopover();renderResults();lastFocusedElement=document.activeElement;el.resultsModal.classList.remove("is-hidden");document.body.classList.add("modal-open");setTimeout(()=>el.closeModalButton.focus(),20)}
function closeResultsModal(){el.resultsModal.classList.add("is-hidden");document.body.classList.remove("modal-open");if(lastFocusedElement&&typeof lastFocusedElement.focus==="function")lastFocusedElement.focus()}
function clearSelection(){selectedHours.clear();updateSelectionUI();hideSlotPopover();closeResultsModal();showToast("Cooking-hour selection cleared.")}
function trapModalFocus(e){if(e.key!=="Tab"||el.resultsModal.classList.contains("is-hidden"))return;const f=el.resultsModal.querySelectorAll('button:not([disabled]),[href],input:not([disabled]),[tabindex]:not([tabindex="-1"])');if(!f.length)return;const first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}
function showToast(msg){clearTimeout(toastTimer);el.toast.textContent=msg;el.toast.classList.add("is-visible");toastTimer=setTimeout(()=>el.toast.classList.remove("is-visible"),2200)}
el.previousButton.addEventListener("click",()=>scrollCarousel(-1));el.nextButton.addEventListener("click",()=>scrollCarousel(1));el.timeViewport.addEventListener("scroll",scheduleCarouselControlUpdate,{passive:true});el.timeViewport.addEventListener("pointerdown",hideSlotPopover);el.timeViewport.addEventListener("keydown",e=>{if(e.key==="ArrowLeft"){e.preventDefault();scrollCarousel(-1)}if(e.key==="ArrowRight"){e.preventDefault();scrollCarousel(1)}});el.goButton.addEventListener("click",openResultsModal);el.closeModalButton.addEventListener("click",closeResultsModal);el.doneButton.addEventListener("click",closeResultsModal);el.resultsModal.addEventListener("click",e=>{if(e.target===el.resultsModal)closeResultsModal()});el.clearButton.addEventListener("click",clearSelection);el.profileButton.addEventListener("click",()=>showToast("Profile editing will be connected to the user service later."));document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!el.resultsModal.classList.contains("is-hidden"))closeResultsModal();trapModalFocus(e)});addEventListener("resize",()=>{hideSlotPopover();scheduleCarouselControlUpdate()});
window.GridCookUI={setUserData,setHourlyTariffs,getSelectedHours:()=>[...selectedHours].sort((a,b)=>a-b),getSelectedTotals:calculateTotals,refreshRemainingHours:()=>{buildAvailableTariffs();renderTimeSlots()}};
setUserData(MOCK_USER);buildAvailableTariffs();renderTimeSlots();
